### PR TITLE
WIP port to 0.7/1.0

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Currently stuck on this:
```
julia> using JuliaDB

julia> a = table([1, 3, 5], [1, 2, 3], names=[:x, :y], pkey=:x, chunks=2);

julia> b = table([2, 3, 4], [1, 2, 3], names=[:x, :y], pkey=:x, chunks=2);

julia> merge(a, b)
ERROR: StackOverflowError:
Stacktrace:
 [1] #38 at /home/jeff/.julia/dev/Dagger/src/thunk.jl:75 [inlined]
 [2] splitchunk(::Dagger.Thunk, ::Array{NamedTuple{(:x,),Tuple{Int64}},1}, ::typeof(IndexedTables.pkeys), ::typeof(JuliaDB.subtable), ::Base.Order.ForwardOrdering) at /home/jeff/.julia/dev/Dagger/src/array/sort.jl:110
 [3] #269 at /home/jeff/.julia/dev/Dagger/src/array/sort.jl:85 [inlined]
```

Happens on both 0.7 and 1.0.

**Comment by shashi** [comment]
I got a longer trace
```julia
ERROR: StackOverflowError:
Stacktrace:
 [1] #cat_t#99(::Val{1}, ::Function, ::Type{Dagger.Thunk}, ::Dagger.Thunk, ::Vararg{Any,N} where N) at ./abstractarray.jl:1353
 [2] (::getfield(Base, Symbol("#kw##cat_t")))(::NamedTuple{(:dims,),Tuple{Val{1}}}, ::typeof(Base.cat_t), ::Type{Dagger.Thunk}, ::Dagger.Thunk, ::Vararg{Any,N} where N) at ./none:0
 [3] _cat(::Val{1}, ::Dagger.Thunk, ::Vararg{Any,N} where N) at ./abstractarray.jl:1351
 [4] #cat#100 at ./abstractarray.jl:1480 [inlined]
 [5] #cat at ./none:0 [inlined]
 [6] vcat at ./abstractarray.jl:1418 [inlined]
 [7] splitchunk(::Dagger.Thunk, ::Array{NamedTuple{(:x,),Tuple{Int64}},1}, ::typeof(IndexedTables.pkeys), ::typeof(JuliaDB.subtable), ::Base.Order.ForwardOrdering) at /home/shashi/.julia/dev/Dagger/src/array/sort.jl:110
```

**Comment by JeffBezanson** [comment]
Added the rest of the trace I got. Seems to be a bit different on 0.7 and 1.0. Mine was from 1.0.

**Comment by shashi** [comment]
the infinite recursion is being caused here: https://github.com/JuliaParallel/Dagger.jl/blob/master/src/array/sort.jl#L67 the `topsplits` and `lowersplits` remain the same.

**Comment by shashi** [comment]
(I'm commenting that file a lot, and should be able to figure out a fix soon. I suspect it has to do something with `isless` on NamedTuples.)

**Comment by JeffBezanson** [comment]
Now I get this in test_readwrite:
```
ERROR: MethodError: Cannot `convert` an object of type Type{Symbol} to an object of type Array{IndexedTables.Perm,1}
Closest candidates are:
  convert(::Type{Array{S,N}}, ::PooledArrays.PooledArray{T,R,N,RA} where RA) where {S, T, R, N} at /home/jeff/.julia/dev/PooledArrays/src/PooledArrays.jl:285
  convert(::Type{Array{S,N}}, ::DataValues.DataValueArray{T,N}) where {S, T, N} at /home/jeff/.julia/packages/DataValues/SNSrX/src/array/primitives.jl:272
  convert(::Type{Array{S,N}}, ::DataValues.DataValueArray{T,N}, ::Any) where {S, T, N} at /home/jeff/.julia/packages/DataValues/SNSrX/src/array/primitives.jl:301
  ...
Stacktrace:
 [1] NextTable{Columns{Tuple{Int64,Int64},Tuple{Array{Int64,1},Array{Int64,1}}}}(::Columns{Tuple{Int64,Int64},Tuple{Array{Int64,1},Array{Int64,1}}}, ::Array{Int64,1}, ::Type, ::Array{Missing,1}, ::Columns{Tuple{Int64,Int64},Tuple{Array{Int64,1},Array{Int64,1}}}) at /home/jeff/.julia/dev/IndexedTables/src/table.jl:25
 [2] #table#102(::Array{Int64,1}, ::Nothing, ::Type, ::Bool, ::Bool, ::Array{Missing,1}, ::Function, ::Val{:serial}, ::Tuple{Array{Int64,1},Array{Int64,1}}) at /home/jeff/.julia/dev/IndexedTables/src/table.jl:219
 [3] (::getfield(IndexedTables, Symbol("#kw##table")))(::NamedTuple{(:chunks, :pkey, :perms, :presorted, :copy),Tuple{Nothing,Array{Int64,1},DataType,Bool,Bool}}, ::typeof(table), ::Val{:serial}, ::Tuple{Array{Int64,1},Array{Int64,1}}) at ./none:0
 [4] #table#106(::Nothing, ::Base.Iterators.Pairs{Symbol,Any,NTuple{4,Symbol},NamedTuple{(:pkey, :perms, :presorted, :copy),Tuple{Array{Int64,1},DataType,Bool,Bool}}}, ::Function, ::Tuple{Array{Int64,1},Array{Int64,1}}) at /home/jeff/.julia/dev/IndexedTables/src/table.jl:247
 [5] (::getfield(IndexedTables, Symbol("#kw##table")))(::NamedTuple{(:pkey, :perms, :presorted, :copy),Tuple{Array{Int64,1},DataType,Bool,Bool}}, ::typeof(table), ::Tuple{Array{Int64,1},Array{Int64,1}}) at ./none:0
 [6] #table#107(::Base.Iterators.Pairs{Symbol,Any,NTuple{4,Symbol},NamedTuple{(:pkey, :perms, :presorted, :copy),Tuple{Array{Int64,1},DataType,Bool,Bool}}}, ::Function, ::Columns{Tuple{Int64,Int64},Tuple{Array{Int64,1},Array{Int64,1}}}) at /home/jeff/.julia/dev/IndexedTables/src/table.jl:250
 [7] (::getfield(IndexedTables, Symbol("#kw##table")))(::NamedTuple{(:pkey, :perms, :presorted, :copy),Tuple{Array{Int64,1},DataType,Bool,Bool}}, ::typeof(table), ::Columns{Tuple{Int64,Int64},Tuple{Array{Int64,1},Array{Int64,1}}}) at ./none:0
 [8] mmread(::Type{NextTable}, ::Serializer{IOStream}, ::Bool) at /home/jeff/.julia/dev/JuliaDB/src/serialize.jl:89
```

`mmread` is somehow getting `Symbol` as the value of a `NextTable.perms` field.

**Comment by o314** [comment]
Thanks you for your stamina to finish the work

**Comment by shashi** [comment]
@o314 LOL, thanks everyone for their patience!

All tests now pass for me with the master of Dagger + IndexedTables. I removed the GC preserve drama from the commits.

**Comment by shashi** [comment]
Oh well spoke too optimistically https://travis-ci.org/JuliaComputing/JuliaDB.jl/jobs/450507856

**Comment by shashi** [comment]
The problem is only in running the ci with the right branches. We should be good to release this once Dagger and IndexedTables releases get merged into metadata.

**Comment by JeffBezanson** [comment]
Awesome!

**Comment by shashi** [comment]
> Dagger and IndexedTables

Also MemPool. Just tagged it.

**Pull request merged**
