### PR TITLE
fix partitionplot for ndsparse

### PR DESCRIPTION
**Pull request by joshday**
@simonbyrne Here is a `partitionplot` that works with ndsparse.

@shashi Can you confirm that `columns` doesn't make copies on distributed tables/ndsparse?  Or is there a smarter way to ask "what is the eltype of selection X?"

### CODE REVIEW

**Comment by simonbyrne** [comment]
```
ArgumentError: wrong number of arguments to named tuple constructor

Stacktrace:
 [1] NamedTuples._NT_pair_timestamp_bid_ask(::Dagger.DArray{DateTime,1,JuliaDB.##59#62}, ::Dagger.DArray{Float32,1,JuliaDB.##59#62}, ::Dagger.DArray{Float32,1,JuliaDB.##59#62}) at /home/simonbyrne/.julia/v0.6/NamedTuples/src/NamedTuples.jl:141
 [2] columns(::JuliaDB.DNDSparse{NamedTuples._NT_pair_timestamp{String,DateTime},NamedTuples._NT_bid_ask{Float32,Float32}}) at /home/simonbyrne/.julia/v0.6/JuliaDB/src/iteration.jl:161
 [3] macro expansion at /home/simonbyrne/.julia/v0.6/JuliaDB/src/recipes.jl:22 [inlined]
 [4] apply_recipe(::Dict{Symbol,Any}, ::JuliaDB.PartitionPlot) at /home/simonbyrne/.julia/v0.6/RecipesBase/src/RecipesBase.jl:287
 [5] _process_userrecipes(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{JuliaDB.PartitionPlot}) at /home/simonbyrne/.julia/v0.6/Plots/src/pipeline.jl:81
 [6] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{JuliaDB.PartitionPlot}) at /home/simonbyrne/.julia/v0.6/Plots/src/plot.jl:179
 [7] (::RecipesBase.#kw##plot)(::Array{Any,1}, ::RecipesBase.#plot, ::JuliaDB.PartitionPlot) at ./<missing>:0
 [8] #partitionplot#363(::Array{Any,1}, ::Function, ::JuliaDB.DNDSparse{NamedTuples._NT_pair_timestamp{String,DateTime},NamedTuples._NT_bid_ask{Float32,Float32}}, ::Vararg{Any,N} where N) at /home/simonbyrne/.julia/v0.6/RecipesBase/src/RecipesBase.jl:363
 [9] (::JuliaDB.#kw##partitionplot)(::Array{Any,1}, ::JuliaDB.#partitionplot, ::JuliaDB.DNDSparse{NamedTuples._NT_pair_timestamp{String,DateTime},NamedTuples._NT_bid_ask{Float32,Float32}}, ::Vararg{Any,N} where N) at ./<missing>:0
```

**Comment by simonbyrne** [comment]
I think that was because I hadn't called `compute`? If I do, then I get:
```
On worker 19:
MethodError: no method matching start(::DateTime)
Closest candidates are:
  start(::SimpleVector) at essentials.jl:258
  start(::Base.MethodList) at reflection.jl:560
  start(::ExponentialBackOff) at error.jl:107
  ...
fit! at /home/simonbyrne/.julia/v0.6/OnlineStatsBase/src/OnlineStatsBase.jl:69
fit! at /home/simonbyrne/.julia/v0.6/OnlineStatsBase/src/OnlineStatsBase.jl:70
init_first at /home/simonbyrne/.julia/v0.6/IndexedTables/src/columns.jl:1159 [inlined]
#reduce#190 at /home/simonbyrne/.julia/v0.6/IndexedTables/src/reduce.jl:104
#reduce at ./<missing>:0
#272 at /home/simonbyrne/.julia/v0.6/JuliaDB/src/reduce.jl:15
do_task at /home/simonbyrne/.julia/v0.6/Dagger/src/scheduler.jl:245
#106 at ./distributed/process_messages.jl:268 [inlined]
run_work_thunk at ./distributed/process_messages.jl:56
macro expansion at ./distributed/process_messages.jl:268 [inlined]
#105 at ./event.jl:73
```

**Comment by joshday** [comment]
The problem occurs when `IndexedPartition` is wrapped in `FTSeries`.  I'm still figuring out why, but `partitionplot` should work with `DNDSparse` now as long as there's no missing data.

**Comment by shashi** [comment]
`columns` is fine. It shouldn't copy or anything.

**Comment by joshday** [comment]
I rewrote `partitionplot` as part of some other updates and have tested it on all four combinations of (distributed) table/ndsparse.  PR coming soon.

**Pull request closed without merging**
